import track1 from "./assets/audio/bad.mp3";
import track2 from "./assets/audio/neverEnough.mp3";

const tracks = [
  {
    id: 1,
    title: "Bad Boy",
    artist: "Bille Ailish",
    src: track1,
    lyricData: [
      { time: 14.42, text: "White shirt now red, my bloody nose" },
      { time: 17.39, text: "Sleeping, you're on your tippy toes" },
      { time: 20.9, text: "Creeping around like no one knows" },
      { time: 24.67, text: "Think you're so criminal" },
      { time: 27.9, text: "Bruises, on both my knees for you" },
      { time: 31.44, text: "Don't say thank you or please" },
      { time: 34.17, text: "I do what I want when I'm wanting to" },
      { time: 38.89, text: "My soul? So cynical" },
      { time: 41.94, text: "So you're a tough guy" },
      { time: 43.42, text: "Like it really rough guy" },
      { time: 45.16, text: "Just can't get enough guy" },
      { time: 46.96, text: "Chest always so puffed guy" },
      { time: 49.14, text: "I'm that bad type" },
      { time: 50.46, text: "Make your mama sad type" },
      { time: 52.18, text: "Make your girlfriend mad tight" },
      { time: 53.94, text: "Might seduce your dad type" },
      { time: 56.45, text: "I'm the bad guy, duh" },
      { time: 73.93, text: "I'm the bad guy" },
      { time: 75.93, text: "I like it when you take control" },
      { time: 77.92, text: "Even if you know that you don't" },
      { time: 81.65, text: "Own me, I'll let you play the role" },
      { time: 85.16, text: "I'll be your animal" },
      { time: 88.15, text: "My mommy likes to sing along with me" },
      { time: 93.14, text: "But she won't sing this song" },
      { time: 95.68, text: "If she reads all the lyrics" },
      { time: 99.14, text: "She'll pity the men I know" },
      { time: 102.14, text: "So you're a tough guy" },
      { time: 103.68, text: "Like it really rough guy" },
      { time: 105.44, text: "Just can't get enough guy" },
      { time: 107.42, text: "Chest always so puffed guy" },
      { time: 109.65, text: "I'm that bad type" },
      { time: 110.89, text: "Make your mama sad type" },
      { time: 112.4, text: "Make your girlfriend mad tight" },
      { time: 114.14, text: "Might seduce your dad type" },
      { time: 116.65, text: "I'm the bad guy, duh" },
      { time: 128.39, text: "I'm the bad guy, duh" },
      { time: 141.17, text: "I'm only good at being bad, bad" },
      { time: 158.39, text: "I like when you get mad" },
      { time: 163.39, text: "I guess I'm pretty glad that you're alone" },
      { time: 167.41, text: "You said she's scared of me?" },
      { time: 169.42, text: "I mean, I don't see what she sees" },
      { time: 172.18, text: "But maybe it's 'cause I'm wearing your cologne" },
      { time: 178.16, text: "I'm a bad guy" },
      { time: 185.08, text: "I'm a bad guy" },
      { time: 186.87, text: "Bad guy, bad guy" },
      { time: 189.39, text: "I'm a bad-" },
    ],
  },
  {
    id: 2,
    title: "Never Enough [The Greatest Showman Soundtrack]",
    artist: "Loren Allred",
    src: track2,
    lyricData: [
      { time: 15.41, text: "I'm trying to hold my breath" },
      { time: 20.88, text: "Let it stay this way" },
      { time: 25.39, text: "Can't let this moment end" },
      { time: 30.39, text: "You set off a dream with me" },
      { time: 36.14, text: "Getting louder now" },
      { time: 39.64, text: "Can you hear it echoing?" },
      { time: 45.88, text: "Take my hand" },
      { time: 49.38, text: "Will you share this with me?" },
      { time: 53.62, text: "'Cause darling without you" },
      { time: 59.12, text: "All the shine of a thousand spotlights" },
      { time: 62.89, text: "All the stars we steal from the nightsky" },
      { time: 66.38, text: "Will never be enough" },
      { time: 70.39, text: "Never be enough" },
      { time: 74.14, text: "Towers of gold are still too little" },
      { time: 77.63, text: "These hands could hold the world but it'll" },
      { time: 81.63, text: "Never be enough" },
      { time: 85.13, text: "Never be enough" },
      { time: 90.37, text: "For me" },
      { time: 92.39, text: "Never, never" },
      { time: 95.88, text: "Never, never" },
      { time: 99.63, text: "Never, for me" },
      { time: 102.9, text: "For me" },
      { time: 105.13, text: "Never enough" },
      { time: 108.62, text: "Never enough" },
      { time: 112.41, text: "Never enough" },
      { time: 115.38, text: "For me" },
      { time: 117.41, text: "For me" },
      { time: 119.13, text: "For me" },
      { time: 123.62, text: "All the shine of a thousand spotlights" },
      { time: 127.14, text: "All the stars we steal from the nightsky" },
      { time: 130.4, text: "Will never be enough" },
      { time: 133.87, text: "Never be enough" },
      { time: 137.9, text: "Towers of gold are still too little" },
      { time: 141.13, text: "These hands could hold the world but it'll" },
      { time: 145.88, text: "Never be enough" },
      { time: 148.38, text: "Never be enough" },
      { time: 155.61, text: "For me" },
      { time: 157.87, text: "Never, never" },
      { time: 161.13, text: "Never, never" },
      { time: 165.13, text: "Never, for me" },
      { time: 168.12, text: "For me" },
      { time: 170.63, text: "Never enough" },
      { time: 172.38, text: "Never, never" },
      { time: 174.13, text: "Never enough" },
      { time: 175.88, text: "Never, never" },
      { time: 177.63, text: "Never enough" },
      { time: 180.88, text: "For me" },
      { time: 182.9, text: "For me" },
      { time: 184.64, text: "For me" },
      { time: 193.88, text: "For me" },
    ],
  },
];

export default tracks;
